"""empty message

Revision ID: 05b2bb1273f7
Revises: 3d962cc50c96
Create Date: 2021-01-20 05:26:06.710853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b2bb1273f7'
down_revision = '3d962cc50c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paciente', 'fecha_nacimieto',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paciente', 'fecha_nacimieto',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
