"""empty message

Revision ID: 08645515ddd0
Revises: 7bff476cf7ea
Create Date: 2021-01-19 18:58:33.620859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08645515ddd0'
down_revision = '7bff476cf7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=False),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=True),
    sa.Column('servicios', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=True),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=True),
    sa.Column('fecha_nacimieto', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=False),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=False),
    sa.Column('id_hospital', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obserbacion', sa.String(length=500), nullable=False),
    sa.Column('paciente', sa.String(), nullable=False),
    sa.Column('medico', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observacion')
    op.drop_table('medico')
    op.drop_table('paciente')
    op.drop_table('hospital')
    # ### end Alembic commands ###
