"""empty message

Revision ID: 24d2ff088fcc
Revises: f390a4d3e00d
Create Date: 2021-01-19 20:18:38.155713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d2ff088fcc'
down_revision = 'f390a4d3e00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observacion', sa.Column('especialidad', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observacion', 'especialidad')
    # ### end Alembic commands ###
