"""empty message

Revision ID: 26b1831151f9
Revises: 6b3cd4c690fc
Create Date: 2021-01-12 03:22:44.646056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b1831151f9'
down_revision = '6b3cd4c690fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'cambioContraseña',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('hospital', 'contrasena')
    op.drop_column('medico', 'contrasena')
    op.alter_column('paciente', 'cambioContraseña',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('paciente', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('paciente', 'contrasena')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('contrasena', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('paciente', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('paciente', 'cambioContraseña',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('medico', sa.Column('contrasena', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('hospital', sa.Column('contrasena', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('hospital', 'cambioContraseña',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
