"""empty message

Revision ID: 63810d7f89c8
Revises: 9a8233dc1291
Create Date: 2021-01-20 05:22:01.295224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63810d7f89c8'
down_revision = '9a8233dc1291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medico', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medico', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('paciente', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('paciente', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paciente', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('paciente', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medico', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medico', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hospital', 'cambio',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
