"""empty message

Revision ID: 65ad32d5ea4b
Revises: 3ec614e73ff7
Create Date: 2021-01-20 05:16:37.197530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ad32d5ea4b'
down_revision = '3ec614e73ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('cambio', sa.Boolean(), nullable=True))
    op.drop_column('hospital', 'cambioContraseña')
    op.add_column('medico', sa.Column('cambio', sa.Boolean(), nullable=True))
    op.alter_column('medico', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('medico', 'cambioContrasena')
    op.add_column('paciente', sa.Column('cambio', sa.Boolean(), nullable=True))
    op.drop_column('paciente', 'cambioContraseña')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('cambioContraseña', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('paciente', 'cambio')
    op.add_column('medico', sa.Column('cambioContrasena', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('medico', 'verificaion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('medico', 'cambio')
    op.add_column('hospital', sa.Column('cambioContraseña', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hospital', 'cambio')
    # ### end Alembic commands ###
