"""empty message

Revision ID: 6b3cd4c690fc
Revises: acb1ed613108
Create Date: 2021-01-11 22:03:33.586660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3cd4c690fc'
down_revision = 'acb1ed613108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obserbacion', sa.String(length=500), nullable=False),
    sa.Column('paciente', sa.String(), nullable=False),
    sa.Column('medico', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observacion')
    # ### end Alembic commands ###
