"""empty message

Revision ID: 7bff476cf7ea
Revises: bc7cc34b18b8
Create Date: 2021-01-19 18:46:08.083782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bff476cf7ea'
down_revision = 'bc7cc34b18b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=True),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=True),
    sa.Column('fecha_nacimieto', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obserbacion', sa.String(length=500), nullable=False),
    sa.Column('paciente', sa.String(), nullable=False),
    sa.Column('medico', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observacion')
    op.drop_table('paciente')
    # ### end Alembic commands ###
