"""empty message

Revision ID: acb1ed613108
Revises: 
Create Date: 2021-01-11 22:01:34.516303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb1ed613108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=False),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=False),
    sa.Column('servicios', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=False),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=False),
    sa.Column('fecha_nacimieto', sa.DateTime(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('verificaion', sa.Boolean(), nullable=False),
    sa.Column('cambioContraseña', sa.Boolean(), nullable=False),
    sa.Column('id_hospital', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medico')
    op.drop_table('paciente')
    op.drop_table('hospital')
    # ### end Alembic commands ###
