"""empty message

Revision ID: f390a4d3e00d
Revises: b1eb7ee6642e
Create Date: 2021-01-19 19:37:00.104536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f390a4d3e00d'
down_revision = 'b1eb7ee6642e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('contrasena', sa.String(length=100), nullable=False))
    op.add_column('medico', sa.Column('contrasena', sa.String(length=100), nullable=False))
    op.add_column('paciente', sa.Column('contrasena', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'contrasena')
    op.drop_column('medico', 'contrasena')
    op.drop_column('hospital', 'contrasena')
    # ### end Alembic commands ###
